# Generated by Django 4.2.1 on 2023-06-01 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_employee_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='UserD',
        ),
    ]
