# Generated by Django 4.2.1 on 2023-06-02 09:19

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_address_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HEAD', 'Header'), ('SIDE', 'Side'), ('FOOT', 'Footer')], default='HEAD', max_length=4)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('wa_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.URLField()),
                ('youtube', models.URLField()),
                ('vk', models.URLField()),
                ('instagram', models.URLField()),
                ('avito', models.URLField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.address')),
            ],
        ),
    ]
