# Generated by Django 4.2.1 on 2023-06-02 10:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_image_product_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
