# Generated by Django 4.2.1 on 2023-06-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.TextField(default=''),
        ),
    ]
