# Generated by Django 4.2.1 on 2023-06-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_size_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('date', models.DateTimeField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('item_detail', models.TextField()),
                ('summ_discount', models.IntegerField()),
                ('summ', models.IntegerField()),
                ('type_of_delivery', models.CharField(choices=[('1', 'Самовывоз'), ('2', 'Доставка')], default='1', max_length=2)),
                ('comment', models.TextField()),
            ],
        ),
    ]
