# Generated by Django 4.2.1 on 2023-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='type_of_delivery',
            field=models.CharField(choices=[('2', 'Доставка'), ('1', 'Самовывоз')], default='1', max_length=2),
        ),
    ]
