# Generated by Django 4.2.1 on 2023-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_list_type_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='City',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order_list',
            name='appartaments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order_list',
            name='house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order_list',
            name='post_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_list',
            name='stree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='type_of_delivery',
            field=models.CharField(choices=[('1', 'Самовывоз'), ('2', 'Доставка')], default='1', max_length=2),
        ),
    ]
