# Generated by Django 4.2.1 on 2023-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_order_list_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articl', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=1000)),
                ('size', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
