# Generated by Django 4.2.1 on 2023-06-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_order_item_id_o_alter_order_list_type_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_list',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='item_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='summ',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='summ_discount',
            field=models.IntegerField(null=True),
        ),
    ]
