# Generated by Django 4.2.1 on 2023-06-21 13:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_order_list_date_alter_order_list_item_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='type_of_delivery',
            field=models.CharField(choices=[('1', 'Самовывоз'), ('2', 'Доставка')], default='1', max_length=2),
        ),
    ]
