# Generated by Django 4.2.1 on 2023-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_order_item_color_alter_order_list_type_of_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='modal_connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('text_area', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order_list',
            name='type_of_delivery',
            field=models.CharField(choices=[('2', 'Доставка'), ('1', 'Самовывоз')], default='1', max_length=2),
        ),
    ]
